// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyWDznNu5wlcYQHlPMavDTvozDI0ZOC8s',
    appId: '1:498461499762:web:91546eb0d72a0646ee7deb',
    messagingSenderId: '498461499762',
    projectId: 'nexlearn-1',
    authDomain: 'nexlearn-1.firebaseapp.com',
    databaseURL: 'https://nexlearn-1-default-rtdb.firebaseio.com',
    storageBucket: 'nexlearn-1.firebasestorage.app',
    measurementId: 'G-4LZV8HLBCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaRD2ZBnoiQKN-OOPLirkXmtBPM23ei4c',
    appId: '1:498461499762:android:7f52d05aefd767a3ee7deb',
    messagingSenderId: '498461499762',
    projectId: 'nexlearn-1',
    databaseURL: 'https://nexlearn-1-default-rtdb.firebaseio.com',
    storageBucket: 'nexlearn-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW_v5p5SqeecT6YhBRBxhlPrzO-CbBn64',
    appId: '1:498461499762:ios:29eac1efe1f19645ee7deb',
    messagingSenderId: '498461499762',
    projectId: 'nexlearn-1',
    databaseURL: 'https://nexlearn-1-default-rtdb.firebaseio.com',
    storageBucket: 'nexlearn-1.firebasestorage.app',
    androidClientId: '498461499762-v7l8te8akh9v0uj1ru8rgn0lg761l0ls.apps.googleusercontent.com',
    iosClientId: '498461499762-im145rf23p5mk9qs0kcn10oucv177kct.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextlearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW_v5p5SqeecT6YhBRBxhlPrzO-CbBn64',
    appId: '1:498461499762:ios:29eac1efe1f19645ee7deb',
    messagingSenderId: '498461499762',
    projectId: 'nexlearn-1',
    databaseURL: 'https://nexlearn-1-default-rtdb.firebaseio.com',
    storageBucket: 'nexlearn-1.firebasestorage.app',
    androidClientId: '498461499762-v7l8te8akh9v0uj1ru8rgn0lg761l0ls.apps.googleusercontent.com',
    iosClientId: '498461499762-im145rf23p5mk9qs0kcn10oucv177kct.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextlearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyWDznNu5wlcYQHlPMavDTvozDI0ZOC8s',
    appId: '1:498461499762:web:91546eb0d72a0646ee7deb',
    messagingSenderId: '498461499762',
    projectId: 'nexlearn-1',
    authDomain: 'nexlearn-1.firebaseapp.com',
    databaseURL: 'https://nexlearn-1-default-rtdb.firebaseio.com',
    storageBucket: 'nexlearn-1.firebasestorage.app',
    measurementId: 'G-4LZV8HLBCN',
  );
}
